name: Deployment to EC2 Instance
run-name: DEPLOY - ${{ github.actor }} is trigger build/deploy with SHA:${{ github.sha }}

on:
  pull_request:
    branches: [main]
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  image_ci:
    uses: ./.github/workflows/image_ci.yaml
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      AWS_ARN: ${{ secrets.AWS_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
      EC2_CONTAINER_NAME: ${{ secrets.EC2_CONTAINER_NAME }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_KEY: ${{ secrets.EC2_KEY }}
      EC2_PORT: ${{ secrets.EC2_PORT }}

  ec2_deploy:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: [image_ci]
    runs-on: ubuntu-20.04
    environment: EC2
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the version
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: get_version
        run: |
          echo "IMAGE_VERSION=$(echo $GITHUB_REF | sed -e 's/refs\/tags\///g')" >> $GITHUB_OUTPUT

      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            docker stop ${{ secrets.EC2_CONTAINER_NAME }} || true
            docker rm -f ${{ secrets.EC2_CONTAINER_NAME }} || true
            docker image prune -a --force
            docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ${{ secrets.DOCKERHUB_USER }}/${{ secrets.EC2_CONTAINER_NAME }}:${{ steps.get_version.outputs.IMAGE_VERSION }}
            export PUBLIC_DNS_ADDRESS=$(ec2-metadata -p | grep -oP '(?<=public-hostname: ).*')
            docker run -d --name ${{ secrets.EC2_CONTAINER_NAME }} -e PUBLIC_DNS_ADDRESS=$PUBLIC_DNS_ADDRESS -p 8888:80 -p 8000:8000 --restart always ${{ secrets.DOCKERHUB_USER }}/${{ secrets.EC2_CONTAINER_NAME }}:${{ steps.get_version.outputs.IMAGE_VERSION }}
